export const ALL_MF_ORDERS = [
  {
    id: 1,
    name: "SBI small Cap Fund Direct Growth",
    date: "17 Dec '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "Completed",
  },
  {
    id: 2,
    name: "Axis midcap Direct plan growth",
    date: "15 Dec '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "In progress",
  },
  {
    id: 3,
    name: "Aditya Birla Sun Life Flexi Cap Fund",
    date: "13 Dec '23",
    amount: "₹2000",
    instalment: "SIP Instalment",
    status: "Completed",
  },
  {
    id: 4,
    name: "Baroda liquid direct fund growth",
    date: "10 Dec '23",
    amount: "₹2000",
    instalment: "SIP Instalment",
    status: "Completed",
  },
  {
    id: 5,
    name: "Icici prudential technology Direct plan growth",
    date: "06 Dec '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "Completed",
  },
  {
    id: 6,
    name: "Parag Parikh Flexi Cap Fund Direct Growth",
    date: "03 Dec '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "In progress",
  },
  {
    id: 7,
    name: "SBI small Cap Fund Direct Growth",
    date: "10 Nov '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "Completed",
  },
  {
    id: 8,
    name: "HDFC flexi Cap Fund Direct Growth",
    date: "15 Nov '23",
    amount: "₹1000",
    instalment: "SIP Instalment",
    status: "In progress",
  },
];

export const ALL_STOCKS_ORDERS = [
  {
    id: 1,
    name: "Balramour Chini Mills",
    date: "13 December, 2023",
    time: "10:13 AM",
    total: "50",
    avgAmount: "₹381.20",
    status: "BUY",
    stocktype: "Delivery",
  },
  {
    id: 2,
    name: "Trident",
    date: "13 December, 2023",
    time: "9:31 AM",
    total: "11",
    avgAmount: "₹36.50",
    status: "BUY",
    stocktype: "Delivery",
  },
  {
    id: 3,
    name: "Tata Technologies",
    date: "13 December, 2023",
    time: "9:31 AM",
    total: "11",
    avgAmount: "₹36.50",
    status: "BUY",
    stocktype: "Delivery",
  },
  {
    id: 4,
    name: "Balramour Chini Mills",
    date: "13 December, 2023",
    time: "10:13 AM",
    total: "50",
    avgAmount: "₹381.20",
    status: "BUY",
    stocktype: "Delivery",
  },
  {
    id: 5,
    name: "Trident",
    date: "13 December, 2023",
    time: "9:31 AM",
    total: "11",
    avgAmount: "₹36.50",
    status: "BUY",
    stocktype: "Delivery",
  },
  {
    id: 6,
    name: "Balramour Chini Mills",
    date: "05 December, 2023",
    time: "11:17 AM",
    total: "1",
    avgAmount: "₹36.50",
    status: "SELL",
    stocktype: "Interaday",
  },
  {
    id: 7,
    name: "Trident",
    date: "05 December, 2023",
    time: "11:17 AM",
    total: "1",
    avgAmount: "₹36.50",
    status: "SELL",
    stocktype: "Delivery",
  },
  {
    id: 8,
    name: "Tata Technologies",
    date: "04 December, 2023",
    time: "9:50 AM",
    total: "3",
    avgAmount: "₹36.50",
    status: "BUY",
    stocktype: "Delivery",
  },
];
