export const CATEGORIES = [
  {
    _id: 1,
    name: "High return",
    logo: "images/high_returns_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "ICICI prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
  {
    _id: 2,
    name: "Tax savings",
    logo: "images/tax_saving_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "Icici prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
  {
    _id: 3,
    name: "Sip with 500",
    logo: "images/sip_with_500_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "Icici prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
  {
    _id: 4,
    name: "Large cap",
    logo: "images/large_cap_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "Icici prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
  {
    _id: 5,
    name: "Mid cap",
    logo: "images/mid_cap_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "Icici prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
  {
    _id: 6,
    name: "Small cap",
    logo: "images/small_cap_dark.svg",
    company: [
      {
        _id: 1,
        logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
        name: "Axis midcap Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 2,
        logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
        name: "Mirae Asset Large Cap Fund.",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 3,
        logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
        name: "Aditya Birla Sun Life Flexi Cap Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 4,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
        name: "Icici prudential technology Direct plan growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 5,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
        name: "Baroda liquid direct fund growth",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
      {
        _id: 6,
        logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
        name: "SBI Equity Hybrid Fund",
        minInvest: "50",
        fundSize: "60225",
        threeYearReturn: "8.48",
        oneDayReturn: "1.16",
        nav: "30.04",
        minSIPAmount: "100",
        rating: "4",
        fundSize: "98111",
        returnAndRating: [
          {
            title: "Fund return",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Category Avg",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
          {
            title: "Rate in category",
            oneYear: "12.5",
            threeYear: "31.3",
            fiveYear: "21.3",
            all: "24.8",
          },
        ],
        investmentCalculator: {
          type: "Monthly SIP",
          amountInvestedPerMonth: "250",
          duration: "6 year",
          expectedReturnRate: "25",
          investmentAmount: "75162",
          estReturns: "95165",
          total: "170327",
        },
        pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
      },
    ],
  },
];

export const ALL_MF_COMPANY = [
  {
    _id: 1,
    logo: "https://companyurlfinder.com/marketing/assets/img/logos/axisdirect.in.png.pagespeed.ce.CLxqY0vOkM.png",
    name: "Axis midcap Direct plan growth",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
  {
    _id: 2,
    logo: "https://static.paytmmoney.com/amc-logo/MIRAS.png",
    name: "Mirae Asset Large Cap Fund.",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
  {
    _id: 3,
    logo: "https://assets1.cleartax-cdn.com/clearsave/images/1637311732_abclogonewfinal01.jpg",
    name: "Aditya Birla Sun Life Flexi Cap Fund",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
  {
    _id: 4,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpSaos9udJ5nQ9LyYNcuTfWy-Ua6nVY3n0mQ&usqp=CAU",
    name: "Icici prudential technology Direct plan growth",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
  {
    _id: 5,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2La5Q_xYCFAJqeytE2pf6SsJAOuo9Pu5KZQ&usqp=CAU",
    name: "Baroda liquid direct fund growth",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
  {
    _id: 6,
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGnGjtgAZ0XVwZ7yEwHhD5cjaxm02Cgw5ajA&usqp=CAU",
    name: "SBI Equity Hybrid Fund",
    minInvest: "50",
    fundSize: "60225",
    threeYearReturn: "8.48",
    oneDayReturn: "1.16",
    nav: "30.04",
    minSIPAmount: "100",
    rating: "4",
    fundSize: "98111",
    returnAndRating: [
      {
        title: "Fund return",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Category Avg",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
      {
        title: "Rate in category",
        oneYear: "12.5",
        threeYear: "31.3",
        fiveYear: "21.3",
        all: "24.8",
      },
    ],
    investmentCalculator: {
      type: "Monthly SIP",
      amountInvestedPerMonth: "250",
      duration: "6 year",
      expectedReturnRate: "25",
      investmentAmount: "75162",
      estReturns: "95165",
      total: "170327",
    },
    pros: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
    cons: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
  },
];
