export const EQUITY = [
  {
    id: 1,
    name: "Meta Platforms",
    type: "holding",
    quantity: 2,
    avg: "2095.00",
    profit: "2126",
    profitPercentage: "+22.00",
    colorStatus: "text-green",
    invested: "20000",
    ltp: "2126.40",
    time: "1 min ago",
  },
  {
    id: 2,
    name: "Tesla",
    type: "current",
    quantity: 2,
    avg: "134.00",
    profit: "100",
    profitPercentage: "-10.00",
    colorStatus: "text-danger",
    invested: "1001",
    ltp: "200.01",
    time: "5 min ago",
  },
  {
    id: 3,
    name: "Infosys",
    type: "booked",
    quantity: 2,
    avg: "2935.00",
    profit: "244",
    profitPercentage: "+12.00",
    colorStatus: "text-green",
    invested: "12234",
    ltp: "13.30",
    time: "7 min ago",
  },
  {
    id: 4,
    name: "Kotak Mahindra",
    type: "holding",
    quantity: 1,
    avg: "356.00",
    profit: "43",
    profitPercentage: "-12.00",
    colorStatus: "text-danger",
    invested: "4545",
    ltp: "367.10",
    time: "39 min ago",
  },
  {
    id: 5,
    name: "Adani Ports",
    type: "booked",
    quantity: 2,
    avg: "768.00",
    profit: "234",
    profitPercentage: "+38.00",
    colorStatus: "text-green",
    invested: "1800",
    ltp: "280.11",
    time: "45 min ago",
  },
  {
    id: 6,
    name: "Balramour Chini Mills",
    type: "booked",
    quantity: 2,
    avg: "343.00",
    profit: "23",
    profitPercentage: "-02.00",
    colorStatus: "text-danger",
    invested: "1000",
    ltp: "122.76",
    time: "47 min ago",
  },
  {
    id: 7,
    name: "Trident",
    type: "holding",
    quantity: 2,
    avg: "4566.00",
    profit: "98",
    profitPercentage: "+09.00",
    colorStatus: "text-green",
    invested: "1800",
    ltp: "98.11",
    time: "55 min ago",
  },
  {
    id: 8,
    name: "Tata Technologies",
    type: "current",
    quantity: 2,
    avg: "800.00",
    profit: "181",
    profitPercentage: "+08.00",
    colorStatus: "text-green",
    invested: "80",
    ltp: "18.02",
    time: "47 min ago",
  },
  {
    id: 9,
    name: "Nvidia",
    type: "holding",
    quantity: 2,
    avg: "900.00",
    profit: "350",
    profitPercentage: "+18.10",
    colorStatus: "text-green",
    invested: "9000",
    ltp: "190.06",
    time: "1 hour ago",
  },
];
